<?php

return [
    'hero' => [
        'navy-senator-suit',
        'utility-camo-vest',
        'foldable-baby-stroller',
        'smart-watch-series',
        'thermal-receipt-printer',
    ],
    'featured' => [
        'navy-senator-suit',
        'foldable-baby-stroller',
        'smart-watch-series',
        'thermal-receipt-printer',
        'philips-avent-gift-set',
        'aptamil-stage-2',
        'cerelac-wheat-1kg',
        'molfix-newborn-pack',
        'huggies-dry-comfort',
        'pampers-giant-pack',
        'semovita-pack',
        'spaghetti-bulk-stock',
    ],
    'items' => [
        [
            'slug' => 'utility-camo-vest',
            'file' => 'IMG-20260331-WA0050.jpg',
            'title' => 'Utility camo vest',
            'category' => 'Fashion',
            'summary' => 'A rugged utility vest with a street-ready camouflage finish.',
        ],
        [
            'slug' => 'moncler-trail-slides',
            'file' => 'IMG-20260331-WA0051.jpg',
            'title' => 'Moncler trail slides',
            'category' => 'Footwear',
            'summary' => 'Chunky black slides with a striking tread and bold finish.',
        ],
        [
            'slug' => 'wrap-two-piece-set',
            'file' => 'IMG-20260331-WA0045.jpg',
            'title' => 'Wrap two-piece set',
            'category' => 'Womenswear',
            'summary' => 'Elegant wrap-style wide-leg set in polished neutral tones.',
        ],
        [
            'slug' => 'tommy-hilfiger-sandals',
            'file' => 'IMG-20260331-WA0035.jpg',
            'title' => 'Tommy Hilfiger sandals',
            'category' => 'Footwear',
            'summary' => 'Glossy black sandals with a clean designer-inspired finish.',
        ],
        [
            'slug' => 'croc-texture-slippers',
            'file' => 'IMG-20260331-WA0034.jpg',
            'title' => 'Croc-texture slippers',
            'category' => 'Footwear',
            'summary' => 'Slip-on sandals with metallic details and a textured look.',
        ],
        [
            'slug' => 'mesh-black-jumpsuit',
            'file' => 'IMG-20260331-WA0030.jpg',
            'title' => 'Mesh black jumpsuit',
            'category' => 'Womenswear',
            'summary' => 'Statement evening jumpsuit with patterned mesh and contour lines.',
        ],
        [
            'slug' => 'blue-leopard-dress',
            'file' => 'IMG-20260331-WA0029.jpg',
            'title' => 'Blue leopard dress',
            'category' => 'Womenswear',
            'summary' => 'Flowing chiffon dress with a vivid blue leopard-inspired print.',
        ],
        [
            'slug' => 'pink-knit-lounge-set',
            'file' => 'IMG-20260331-WA0026.jpg',
            'title' => 'Pink knit lounge set',
            'category' => 'Womenswear',
            'summary' => 'Soft pink fitted set with a relaxed lounge-meets-street feel.',
        ],
        [
            'slug' => 'marble-two-piece-set',
            'file' => 'IMG-20260331-WA0025.jpg',
            'title' => 'Marble two-piece set',
            'category' => 'Womenswear',
            'summary' => 'Printed shirt-and-trouser set with a warm marble finish.',
        ],
        [
            'slug' => 'wardrobe-display-unit',
            'file' => 'IMG-20260331-WA0018.jpg',
            'title' => 'Wardrobe display unit',
            'category' => 'Furniture',
            'summary' => 'Tall open wardrobe shelving designed for storage and display.',
        ],
        [
            'slug' => 'open-storage-shelf',
            'file' => 'IMG-20260331-WA0017.jpg',
            'title' => 'Open storage shelf',
            'category' => 'Furniture',
            'summary' => 'Simple shelving unit for room organization and small-space storage.',
        ],
        [
            'slug' => 'curated-style-pick-1',
            'file' => '1.jpg',
            'title' => 'Curated style pick 1',
            'category' => 'Fashion',
            'summary' => 'A fresh fashion arrival selected for the featured lineup.',
        ],
        [
            'slug' => 'curated-style-pick-2',
            'file' => 'images (6).jpg',
            'title' => 'Curated style pick 2',
            'category' => 'Fashion',
            'summary' => 'Another handpicked featured item from the latest arrivals.',
        ],
        [
            'slug' => 'navy-senator-suit',
            'file' => 'Daro Uomo Two Piece Short-Sleeve Senator Suit Navy Blue (1)-1080x1440.jpg',
            'title' => 'Daro Uomo navy senator suit',
            'category' => 'Menswear',
            'summary' => 'Short-sleeve senator suit with a polished navy tailored finish.',
            'price_label' => '₦98,000.00',
            'price_source_name' => 'Dexstitches',
            'price_source_url' => 'https://dexstitches.com/daro-uomo-two-piece-short-sleeve-senator-suit-navy-blue',
        ],
        [
            'slug' => 'curated-style-pick-3',
            'file' => 'images (5).jpg',
            'title' => 'Curated style pick 3',
            'category' => 'Fashion',
            'summary' => 'Featured selection from the current curated inventory drop.',
        ],
        [
            'slug' => 'baby-walker-spark',
            'file' => '068111a4-11f0-44ea-a597-3decbb1a4022.f4c4c35caeea876f4e3d0598b350eb66.webp',
            'title' => 'Baby walker spark',
            'category' => 'Baby gear',
            'summary' => 'Colorful baby walker made for early mobility and play.',
        ],
        [
            'slug' => 'baby-walker-music',
            'file' => 'walkers-with-toys-and-music-kb7-878140.webp',
            'title' => 'Walker with toys and music',
            'category' => 'Baby gear',
            'summary' => 'Playful walker with toy features for active little explorers.',
        ],
        [
            'slug' => 'travel-stroller-blue',
            'file' => 's-l1600_0efce555-8a13-4a27-a556-593ae1fd6ffa.webp',
            'title' => 'Travel stroller blue',
            'category' => 'Baby gear',
            'summary' => 'Compact stroller setup built for easy movement and travel days.',
        ],
        [
            'slug' => 'foldable-baby-stroller',
            'file' => 'Foldable-Baby-Stroller-with-Adjustable-Canopy.webp',
            'title' => 'Foldable baby stroller',
            'category' => 'Baby gear',
            'summary' => 'Foldable stroller with canopy support and a cleaner travel setup.',
            'price_label' => 'From £79.99',
            'price_source_name' => 'Aosom UK',
            'price_source_url' => 'https://www.aosom.co.uk/item/aiyaplay-foldable-baby-stroller-with-adjustable-seat-5-point-harness-canopy-basket-6-3kg-lightweight-compact-light-grey~20I244BDA3O01.html',
        ],
        [
            'slug' => 'philips-avent-gift-set',
            'file' => '166395525-166395525-BSRG2152024_01-2100.webp',
            'title' => 'Philips Avent gift set',
            'category' => 'Baby care',
            'summary' => 'Feeding gift set designed for practical newborn care routines.',
            'price_label' => '$19.95',
            'price_source_name' => 'Babylist',
            'price_source_url' => 'https://www.babylist.com/gp/philips-avent-natural-baby-bottle-with-natural-response-nipple-teal-baby-gift-set/55656/2085109',
        ],
        [
            'slug' => 'baby-feeding-starter-pack',
            'file' => '190957132_MzAwLTMwMC05ZDQ0NjhjYmU3.webp',
            'title' => 'Baby feeding starter pack',
            'category' => 'Baby care',
            'summary' => 'Starter feeding essentials bundled for infant care convenience.',
        ],
        [
            'slug' => 'aptamil-stage-2',
            'file' => 'aptamil_uk_2025_stage2_6-12_months_formula_milk_ie_640x640px.webp',
            'title' => 'Aptamil stage 2',
            'category' => 'Baby nutrition',
            'summary' => 'Follow-on milk option for growing babies in active feeding stages.',
            'price_label' => '£7.25',
            'price_source_name' => 'Tesco',
            'price_source_url' => 'https://www.tesco.com/shop/en-GB/products/310687749',
        ],
        [
            'slug' => 'cerelac-wheat-1kg',
            'file' => 'cerelac-wheat-1kg.jpg',
            'title' => 'Cerelac wheat cereal',
            'category' => 'Baby nutrition',
            'summary' => 'Wheat infant cereal selected for the curated nutrition range.',
            'price_label' => '₦6,709.99',
            'price_source_name' => 'Addide',
            'price_source_url' => 'https://addide.com/products/nestle-cerelac-wheat-milk-400',
        ],
        [
            'slug' => 'cerelac-wheat-tin',
            'file' => '71I9YI5RsBL._AC_UF894,1000_QL80_.jpg',
            'title' => 'Cerelac wheat tin',
            'category' => 'Baby nutrition',
            'summary' => 'Compact Cerelac tin format for infant cereal supply.',
        ],
        [
            'slug' => 'newborn-blue-outfit-set',
            'file' => 'yCpg36RDkNDX5UXNCNE6mijLc1smgNY9ytPq6eRQ.png',
            'title' => 'Newborn blue outfit set',
            'category' => 'Baby wear',
            'summary' => 'Soft coordinated baby clothing set for everyday newborn comfort.',
        ],
        [
            'slug' => 'baby-bath-set',
            'file' => '8001090910981_2.jpg',
            'title' => 'Baby bath starter set',
            'category' => 'Baby care',
            'summary' => 'Bath and care essentials grouped into one starter bundle.',
        ],
        [
            'slug' => 'ankara-fabric-stack',
            'file' => 'images (4).jpg',
            'title' => 'Ankara fabric stack',
            'category' => 'Fabric',
            'summary' => 'Vibrant folded Ankara prints arranged for fashion and tailoring.',
        ],
        [
            'slug' => 'huggies-dry-comfort',
            'file' => 'PLP_Product-Card_Dry-Comfort-Pants_288-x-288px.jpg',
            'title' => 'Huggies dry comfort',
            'category' => 'Baby care',
            'summary' => 'Dry comfort pants included in the curated diaper essentials.',
            'price_label' => '₦6,999.99',
            'price_source_name' => 'Addide',
            'price_source_url' => 'https://addide.com/products/huggies-dry-comfort-5-jumbo-size',
        ],
        [
            'slug' => 'molfix-midi-pack',
            'file' => '1479313986708_spxspz1009_molfix_size_3_midi_4-9_kg_92_pieces_169x226_2.jpg',
            'title' => 'Molfix midi pack',
            'category' => 'Baby care',
            'summary' => 'Midi-size diaper pack for active everyday baby care.',
        ],
        [
            'slug' => 'molfix-newborn-pack',
            'file' => 'NEWBORN2-5KG.webp',
            'title' => 'Molfix newborn pack',
            'category' => 'Baby care',
            'summary' => 'Newborn diaper option for early-stage baby comfort and care.',
            'price_label' => '₦1,269.99',
            'price_source_name' => 'Addide',
            'price_source_url' => 'https://addide.com/products/molfix-diaper-newborn-2-5kg',
        ],
        [
            'slug' => 'molfix-mini-jumbo',
            'file' => 'DIAPERMINIJIUMBO.webp',
            'title' => 'Molfix mini jumbo',
            'category' => 'Baby care',
            'summary' => 'Mini jumbo diaper pack selected for growing baby essentials.',
        ],
        [
            'slug' => 'frozen-chicken-wings',
            'file' => 'wings-300x272.png',
            'title' => 'Frozen chicken wings',
            'category' => 'Groceries',
            'summary' => 'Bulk frozen chicken wings for home kitchens and food supply.',
        ],
        [
            'slug' => 'pampers-monthly-pack',
            'file' => 'images (3).jpg',
            'title' => 'Pampers monthly pack',
            'category' => 'Baby care',
            'summary' => 'Monthly baby diaper pack for household stock-up needs.',
        ],
        [
            'slug' => 'pampers-giant-pack',
            'file' => 'images (2).jpg',
            'title' => 'Pampers giant pack',
            'category' => 'Baby care',
            'summary' => 'Giant pack diapers chosen for practical everyday family supply.',
            'price_label' => '€20.99',
            'price_source_name' => 'Pepita',
            'price_source_url' => 'https://pepita.com/en/diapers-c1382/pampers-active-baby-giant-pack-11-16kg-junior-5-64pcs-p698076',
        ],
        [
            'slug' => 'spaghetti-bulk-stock',
            'file' => 'Glq0kIkWsAA3GMN.jpg',
            'title' => 'Spaghetti bulk stock',
            'category' => 'Groceries',
            'summary' => 'Bulk spaghetti packs ready for pantry restock and resale.',
            'price_label' => 'From ₦1,499.99',
            'price_source_name' => 'Addide',
            'price_source_url' => 'https://addide.com/collections/all/products/golden-penny-spaghetti-500g',
        ],
        [
            'slug' => 'semovita-pack',
            'file' => 'images (1).jpg',
            'title' => 'Semovita pack',
            'category' => 'Groceries',
            'summary' => 'Packaged semovita included in the staple food selection.',
            'price_label' => '₦2,519.99',
            'price_source_name' => 'Addide',
            'price_source_url' => 'https://addide.com/products/golden-penny-semovita-2kg',
        ],
        [
            'slug' => 'garri-sacks',
            'file' => 'images.jpg',
            'title' => 'Garri sacks',
            'category' => 'Groceries',
            'summary' => 'Bagged garri supply for household use and food trade.',
        ],
        [
            'slug' => 'rice-grain-stock',
            'file' => 'fr.png',
            'title' => 'Rice grain stock',
            'category' => 'Groceries',
            'summary' => 'Measured rice grain stock for staple household supply.',
        ],
        [
            'slug' => 'smart-watch-series',
            'file' => '64892699a351d816272a7e83-ddidbi-smart-watch-for-men.jpg',
            'title' => 'Smart watch series',
            'category' => 'Electronics',
            'summary' => 'Smart watch with fitness, call, and display-focused features.',
            'price_label' => 'From $28.49',
            'price_source_name' => 'Amazon',
            'price_source_url' => 'https://us.amazon.com/fitcloudpro-smart-watch/s?k=fitcloudpro+smart+watch&page=2',
        ],
        [
            'slug' => 'thermal-receipt-printer',
            'file' => '65d3e65f4e09b678e957538d-volcora-thermal-receipt-printer-80mm.jpg',
            'title' => 'Thermal receipt printer',
            'category' => 'Business tools',
            'summary' => 'Fast receipt printing hardware for retail counters and POS use.',
            'price_label' => 'From $75.95',
            'price_source_name' => 'Volcora',
            'price_source_url' => 'https://volcora.com/products/thermal-receipt-printer',
        ],
        [
            'slug' => 'thermal-printer-unit',
            'file' => '71R0sU9KEQL._AC_SL1500_.jpg',
            'title' => 'POS printer unit',
            'category' => 'Business tools',
            'summary' => 'Compact POS printer for fast ticketing and receipt workflows.',
        ],
        [
            'slug' => 'mobile-power-box-tower',
            'file' => 'IMG-20260329-WA0080.jpg',
            'title' => 'Mobile power box tower',
            'category' => 'Power',
            'summary' => 'Heavy-duty mobile power box setup for off-grid backup needs.',
        ],
        [
            'slug' => 'mobile-power-box-stack',
            'file' => 'IMG-20260325-WA0041.jpg',
            'title' => 'Mobile power box stack',
            'category' => 'Power',
            'summary' => 'Stacked power box units prepared for compact backup deployment.',
        ],
        [
            'slug' => 'mobile-power-box-trio',
            'file' => 'IMG-20260325-WA0037.jpg',
            'title' => 'Mobile power box trio',
            'category' => 'Power',
            'summary' => 'Three portable power units arranged for home and office support.',
        ],
    ],
];
