<?php

return [
    'category_defaults' => [
        'electronics' => 'assets/images/catalog/tech-device.svg',
        'phones-and-tablets' => 'assets/images/catalog/tech-phone.svg',
        'home-appliances' => 'assets/images/catalog/home-appliance.svg',
        'computing-and-accessories' => 'assets/images/catalog/computing-tools.svg',
        'office-equipment' => 'assets/images/catalog/office-tools.svg',
        'bags-and-backpacks' => 'assets/images/catalog/bag-luggage.svg',
        'shoes-and-footwear' => 'assets/images/catalog/footwear-style.svg',
        'watches-and-accessories' => 'assets/images/catalog/watch-accessory.svg',
        'fashion' => 'assets/images/catalog/fashion-apparel.svg',
        'raw-food-items' => 'assets/images/catalog/grocery-staples.svg',
        'baby-care-and-diapers' => 'assets/images/catalog/baby-care.svg',
        'baby-items-and-accessories' => 'assets/images/catalog/baby-care.svg',
    ],

    'exact' => [
        'thermal-receipt-printer-80mm-ksk-trp-002' => '65d3e65f4e09b678e957538d-volcora-thermal-receipt-printer-80mm.jpg',
        'smart-watch-series-8-pro-ksk-sfw-004' => '64892699a351d816272a7e83-ddidbi-smart-watch-for-men.jpg',
        'premium-parboiled-rice-50kg-loc-food-001' => 'fr.png',
        'foreign-rice-25kg-loc-food-002' => 'fr.png',
        'white-garri-10kg-loc-food-004' => 'images.jpg',
        'semovita-5kg-loc-food-005' => 'images (1).jpg',
        'golden-penny-spaghetti-carton-20-x-500g-loc-food-006' => 'Glq0kIkWsAA3GMN.jpg',
        'groundnut-oil-5l-loc-food-007' => 'images (5).jpg',
        'palm-oil-5l-loc-food-008' => 'images (5).jpg',
        'frozen-chicken-10kg-loc-food-009' => 'wings-300x272.png',
        'turkey-wings-5kg-loc-food-010' => 'wings-300x272.png',
        'molfix-air-dry-size-3-50pcs-loc-baby-001' => '1479313986708_spxspz1009_molfix_size_3_midi_4-9_kg_92_pieces_169x226_2.jpg',
        'huggies-dry-comfort-size-4-62pcs-loc-baby-002' => 'PLP_Product-Card_Dry-Comfort-Pants_288-x-288px.jpg',
        'pampers-baby-dry-size-5-64pcs-loc-baby-003' => 'images (2).jpg',
        'cussons-baby-wipes-80pcs-triple-pack-loc-baby-004' => 'images (3).jpg',
        'cerelac-wheat-with-milk-1kg-loc-baby-005' => 'cerelac-wheat-1kg.jpg',
        'aptamil-infant-formula-900g-loc-baby-006' => 'aptamil_uk_2025_stage2_6-12_months_formula_milk_ie_640x640px.webp',
        'baby-feeding-bottle-set-3pcs-loc-bacc-001' => '190957132_MzAwLTMwMC05ZDQ0NjhjYmU3.webp',
        'foldable-baby-stroller-loc-bacc-002' => 'Foldable-Baby-Stroller-with-Adjustable-Canopy.webp',
        'musical-baby-walker-loc-bacc-003' => 'walkers-with-toys-and-music-kb7-878140.webp',
        'newborn-bodysuit-set-5pcs-loc-bacc-004' => 'yCpg36RDkNDX5UXNCNE6mijLc1smgNY9ytPq6eRQ.png',
        'baby-bath-tub-and-potty-set-loc-bacc-005' => '8001090910981_2.jpg',
        'mens-senator-wear-navy-loc-fash-001' => 'Daro Uomo Two Piece Short-Sleeve Senator Suit Navy Blue (1)-1080x1440.jpg',
        'womens-ankara-maxi-gown-emerald-loc-fash-002' => 'IMG-20260331-WA0029.jpg',
        'straight-cut-denim-jeans-blue-loc-fash-004' => 'images (6).jpg',
        'womens-two-piece-lounge-set-beige-loc-fash-006' => 'IMG-20260331-WA0026.jpg',
        'smart-watch-ultra-fit-loc-wat-004' => '64892699a351d816272a7e83-ddidbi-smart-watch-for-men.jpg',
        'womens-block-heel-sandals-loc-shoe-002' => 'IMG-20260331-WA0035.jpg',
        'childrens-school-shoes-black-loc-shoe-004' => 'IMG-20260331-WA0035.jpg',
        'womens-heeled-sandals-jij-shoe-002' => 'IMG-20260331-WA0034.jpg',
    ],

    'keyword' => [
        ['keywords' => ['molfix'], 'file' => '1479313986708_spxspz1009_molfix_size_3_midi_4-9_kg_92_pieces_169x226_2.jpg'],
        ['keywords' => ['huggies'], 'file' => 'PLP_Product-Card_Dry-Comfort-Pants_288-x-288px.jpg'],
        ['keywords' => ['pampers'], 'file' => 'images (2).jpg'],
        ['keywords' => ['wipes'], 'file' => 'images (3).jpg'],
        ['keywords' => ['cerelac'], 'file' => 'cerelac-wheat-1kg.jpg'],
        ['keywords' => ['aptamil'], 'file' => 'aptamil_uk_2025_stage2_6-12_months_formula_milk_ie_640x640px.webp'],
        ['keywords' => ['stroller'], 'file' => 'Foldable-Baby-Stroller-with-Adjustable-Canopy.webp'],
        ['keywords' => ['walker'], 'file' => 'walkers-with-toys-and-music-kb7-878140.webp'],
        ['keywords' => ['bottle', 'feeding'], 'file' => '190957132_MzAwLTMwMC05ZDQ0NjhjYmU3.webp'],
        ['keywords' => ['newborn', 'bodysuit'], 'file' => 'yCpg36RDkNDX5UXNCNE6mijLc1smgNY9ytPq6eRQ.png'],
        ['keywords' => ['bath tub', 'potty', 'bath set'], 'file' => '8001090910981_2.jpg'],
        ['keywords' => ['senator', 'mens senator'], 'file' => 'Daro Uomo Two Piece Short-Sleeve Senator Suit Navy Blue (1)-1080x1440.jpg'],
        ['keywords' => ['ankara', 'gown', 'dress'], 'file' => 'IMG-20260331-WA0029.jpg'],
        ['keywords' => ['lounge set', 'two-piece', 'work blazer'], 'file' => 'IMG-20260331-WA0025.jpg'],
        ['keywords' => ['shirt', 't-shirt'], 'file' => 'IMG-20260331-WA0050.jpg'],
        ['keywords' => ['jeans', 'denim'], 'file' => 'images (6).jpg'],
        ['keywords' => ['watch'], 'file' => '64892699a351d816272a7e83-ddidbi-smart-watch-for-men.jpg'],
        ['keywords' => ['sandals', 'heels', 'shoe', 'sneakers', 'trainers', 'loafers', 'derby'], 'file' => 'IMG-20260331-WA0035.jpg'],
        ['keywords' => ['spaghetti'], 'file' => 'Glq0kIkWsAA3GMN.jpg'],
        ['keywords' => ['semovita'], 'file' => 'images (1).jpg'],
        ['keywords' => ['rice'], 'file' => 'fr.png'],
        ['keywords' => ['garri'], 'file' => 'images.jpg'],
        ['keywords' => ['beans'], 'file' => 'fr.png'],
        ['keywords' => ['groundnut oil', 'vegetable oil'], 'file' => 'images (5).jpg'],
        ['keywords' => ['palm oil'], 'file' => 'images (5).jpg'],
        ['keywords' => ['chicken', 'turkey wings'], 'file' => 'wings-300x272.png'],
        ['keywords' => ['printer', 'receipt', 'barcode', 'label', 'cash drawer', 'copy paper', 'laminating', 'pos'], 'file' => '65d3e65f4e09b678e957538d-volcora-thermal-receipt-printer-80mm.jpg'],
        ['keywords' => ['power box', 'ups'], 'file' => 'IMG-20260325-WA0041.jpg'],
    ],
];
